---
kind: pipeline
type: docker
name: amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: Remove unmodified packages
    image: alpine/git
    commands:
      - |
        for pkg in packages/*; do
          if git diff --quiet ${DRONE_COMMIT_BEFORE}..${DRONE_COMMIT_AFTER} $pkg && [ -n "${CI}" ]; then
            rm -r $pkg
          fi
        done
      - echo "Building:"
      - ls -1 packages
  - name: Build packages
    image: alpinelinux/build-base
    commands:
      - abuild-keygen -nai
      - |
        for pkg in packages/*; do (
          cd $pkg; abuild -r
        ); done

trigger:
  event:
    - push
    - pull_request
  branch:
    - master

---
kind: pipeline
type: docker
name: arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: Remove unmodified packages
    image: alpine/git
    commands:
      - |
        for pkg in packages/*; do
          if git diff --quiet ${DRONE_COMMIT_BEFORE}..${DRONE_COMMIT_AFTER} $pkg && [ -n "${CI}" ]; then
            rm -r $pkg
          fi
        done
      - echo "Building:"
      - ls -1 packages
  - name: Build packages
    image: alpinelinux/build-base
    commands:
      - abuild-keygen -nai
      - |
        for pkg in packages/*; do (
          cd $pkg; abuild -r
        ); done

trigger:
  event:
    - push
    - pull_request
  branch:
    - master
