---
kind: pipeline
type: docker
name: amd64

platform:
  os: linux
  arch: amd64

environment:
  SOURCE_DATE_EPOCH: ${DRONE_BUILD_CREATED}
  MAKEFLAGS: "-j4"
  SRCDEST: /tmp/build

steps:
  - name: Build packages
    image: alpinelinux/build-base
    commands:
      - abuild-keygen -nai
      - echo "https://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
      - abuild-apk update
      - |
        for pkg in packages/*; do (
          if ! git diff --quiet ${DRONE_COMMIT_BEFORE}..${DRONE_COMMIT_AFTER} $pkg; then
            cd $pkg; abuild -crs ~/src
          fi
        ); done

trigger:
  event:
    - push
    - pull_request
  branch:
    - master

---
kind: pipeline
type: docker
name: arm64

platform:
  os: linux
  arch: arm64

environment:
  SOURCE_DATE_EPOCH: ${DRONE_BUILD_CREATED}
  MAKEFLAGS: "-j4"

steps:
  - name: Build packages
    image: alpinelinux/build-base
    commands:
      - abuild-keygen -nai
      - echo "https://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
      - abuild-apk update
      - |
        for pkg in packages/*; do (
          if ! git diff --quiet ${DRONE_COMMIT_BEFORE}..${DRONE_COMMIT_AFTER} $pkg; then
            cd $pkg; abuild -crs ~/src
          fi
        ); done

trigger:
  event:
    - push
    - pull_request
  branch:
    - master
